---
- hosts: aws-cli
  gather_facts: False

# NOTE: this cant be run independently and only against Live isntances
# This is dependent on IAMuserSecretKey variable being created by the Create_AWS_IAM_Programmatic.yml
# It is inteded to connect to an existing DB and update the S3 config variables
# Variables to be passed:
# {{ IAMuserSecretKey }}
# {{ DBHost }}
# {{ DBPass }}
# {{ DBUser}}
# {{ InstanceID }}
# {{ AWSregion }}

  tasks:
  - name: "Verify user Key and Secret"
    debug:
      msg: "Key: {{ IAMuserSecretKey.user_meta.access_keys[0].access_key_id }} Secret: {{ IAMuserSecretKey.user_meta.access_keys[0].secret_access_key }}"

  - name: "Write RDS creds to DB"
    shell: |
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='{{ IAMuserSecretKey.user_meta.access_keys[0].access_key_id | quote }}' where name='otfs_s3_cred_key';"  2> /dev/null
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='{{ IAMuserSecretKey.user_meta.access_keys[0].secret_access_key | quote }}' where name='otfs_s3_cred_secret';"  2> /dev/null
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='{{ AWSregion | quote }}' where name='otfs_s3_region';"  2> /dev/null
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='latest' where name='otfs_s3_version';"  2> /dev/null
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='sbx.{{ AWSregion }}.{{ SchoolCode }}' where name='otfs_s3_bucket';"  2> /dev/null
      mysql --host={{ DBHost }} -u {{ DBUser}} -p{{ DBPass }} sandbox_{{ SchoolCode }} -BNe "UPDATE config SET value='schoolbox' where name='otfs_s3_prefix';"  2> /dev/null
