---
- hosts: aws-cli
  gather_facts: False

  # Create a new ACM public cert
  # variables to be passed:
  # {{ AWSregion }}
  # {{ SchoolCode }}
  # {{ Domain }}
  # {{ ALB }}

  tasks:
    - name: Add cert to websocket Listner
      shell: >
        aws elbv2 add-listener-certificates --listener-arn {{ websocketListnerARN }} --certificates CertificateArn={{ CertARN }}
      register: DelWebsocketListner
      until: DelWebsocketListner is not failed
      retries: 5
